services:
  - type: web
    name: mediconnect-api
    env: node
    rootDir: MediConnect/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
